#!/bin/bash

# ensure parameter
if [ $# != 1 ];then
    echo "Specify the project name."
    exit 1
fi

# compatible with zsh
export DISABLE_AUTO_TITLE="true"

project=$1
dir='~/Desktop/Project/'${project}

# if the session is already existed, attach to it
tmux has-session -t $project
if [ $? = 0 ];then
    tmux attach-session -t $project
    exit
fi

tmux new-session -d -s $project -n edit
# tmux new-session: craete a new session
# -d: detach from this session
# -s: session name
# -n: default window name
tmux split-window -h -t $project:0 -p 80
# tmux split-window: split widnow
# -h: split horizontally( left and right )
# -t: target session. sessionName:windowIndex.panelIndex
# -p: size percentage of the new panel
tmux send-keys -t $project:0.0 'cd '${dir} C-m
# tmux send-keys: send keys to specified panel
# -t: target session
# C-m: \n
tmux send-keys -t $project:0.0 'clear' C-m
tmux send-keys -t $project:0.1 'cd '${dir} C-m
tmux send-keys -t $project:0.1 'clear' C-m
tmux send-keys -t $project:0.1 'vim' C-m

tmux select-window -t $project:0
tmux attach-session -t $project
